### ISSUE TITLE
Allow unbalanced vouchers when reading documents

### ISSUE THREAD

**Issue by JakobStrasser** [idstam/jsisie#11]
Great library and I've used it in many projects!

I'm having an issue where some SIE-files include unbalanced vouchers but I still want to be able to parse these.

I can fix it myself if that's OK. I would like to add a new flag, IgnoreUnbalancedVoucher, and check this flag in closeVoucher method.

**Comment by idstam** [comment]
I like the sugestion but:

IgnoreUnbalancedVoucher implies that we should not handle those transactions at all, like we do with IgnoreBTRANS.
I thought about naming the flag either IgnoreUnbalancedVoucherException or AllowUnbalancedVoucher.

The later is shorter and feels more "business language" to me. 

... yes I named IgnoreMissingDate badly so I added AllowMissingDate that will mirror IgnoreMissingDate.

**Comment by JakobStrasser** [comment]
Thanks!
