### ISSUE TITLE
Outdated Nuget package?

### ISSUE THREAD

**Issue by chrobakos** [idstam/jsisie#4]
Hi @idstam ! Thanks for a nice library.
I downloaded _jsisie_ package via NuGet Package Manager and the most recent version seems to be 2.2.0 there. However, I can see some differences between the version in Nuget and the version here on Github (e.g. method SieDocument.ReadDocument accepts only string as parameter, but in source code here I can see it can take also Stream (and I specifically need that:) )). 
Is it possible that version on Nuget is not up-to-date?

Thanks!

**Comment by idstam** [comment]
Thanks.

I'll try to make that happen tonight (CET)

**Comment by idstam** [comment]
2.3.0 should be available from nuget.org now.

I made it in .net standard 2.0 instead of .net framework, but it should still work for .net framework clients.

**Comment by idstam** [comment]
... but there is no read from stream. It's only awrite.

**Comment by chrobakos** [comment]
Isn't this for reading from stream?

SieDocument.cs, Starting with line 194


```
public void ReadDocument(Stream stream)
        {
            _fileName = "(stream)";
            ReadStreamAux(stream);
        }
```

**Comment by idstam** [comment]
Ah, I messed up. Missed a merge and deleted some files. :)  
New one coming up soon.

**Comment by idstam** [comment]
So sorry about that. I still had the old Master branch here not the new Main.

2.3.2 is on it's way out on nuget.org
