### ISSUE TITLE
A.68 Sum is not zero

### ISSUE THREAD

**Issue by TeemuLattiLuja** [idstam/jsisie#5]
Hello

I get an exception _jsiSIE.SieVoucherMissmatchException 'A.68 Sum is not zero'_ when trying to get voucherRows using jsisie. Can you help me to understand what's the issue?
```
//Getting connector
            var sieConnector = fortnoxClient.Get<SIEConnector>();
            var data = sieConnector.Get(SIEType.Transactions, 6);

            //SIE from Fortnox is encoded in PC-8 (Code page 437) 
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

            var sieDocument = new SieDocument();
            sieDocument.ReadDocument(new MemoryStream(data));

            foreach (var sieVoucher in sieDocument.VER)
            {
                var series = sieVoucher.Series;
                var date = sieVoucher.VoucherDate;
                //...//

                foreach (var sieVoucherRow in sieVoucher.Rows)
                {
                    var amount = sieVoucherRow.Amount;
                    var account = sieVoucherRow.Account.Number;
                    var text = sieVoucherRow.Text;
                    
                    // ... //
                }
            }
```

**Comment by idstam** [comment]
Hi


Debit and Kredit has be equaly large, one positive and the other negative, on a voucher. 

I check that by adding all Amount on all Rows. If it doesn't end up at zero the voucher is invalid.



Does your A.68 balance?



You can email me at ***@***.*** instead.



/johan/


From: TeemuLattiLuja ***@***.***>
To: idstam/jsisie ***@***.***>
Subject: [idstam/jsisie] A.68 Sum is not zero (#5)
Date: 01/06/2021 12:48:43 Europe/Stockholm
Cc: Subscribed ***@***.***>


Hello

I get an exception jsiSIE.SieVoucherMissmatchException 'A.68 Sum is not zero' when trying to get voucherRows using jsisie. Can you help me to understand what's the issue?
//Getting connector
            var sieConnector = fortnoxClient.Get<SIEConnector>();
            var data = sieConnector.Get(SIEType.Transactions, 6);

            //SIE from Fortnox is encoded in PC-8 (Code page 437) 
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

            var sieDocument = new SieDocument();
            sieDocument.ReadDocument(new MemoryStream(data));

            foreach (var sieVoucher in sieDocument.VER)
            {
                var series = sieVoucher.Series;
                var date = sieVoucher.VoucherDate;
                //...//

                foreach (var sieVoucherRow in sieVoucher.Rows)
                {
                    var amount = sieVoucherRow.Amount;
                    var account = sieVoucherRow.Account.Number;
                    var text = sieVoucherRow.Text;
                    
                    // ... //
                }
            }

**Comment by TeemuLattiLuja** [comment]
Hi

Yes it is in balance. Any ideas what next?

**Comment by idstam** [comment]
It's impossible to guess without any more data.
I would get the code from here and use that instead of the nuget-package.
Search for 'Sum is not zero' and set breakpoints outside of the loops on those two places. 
Try to see why the rows doesn't sum to zero.

I need a failing SIE file to do debugging and at least the A.68 parts from the file to do some more guessing. 
If you want to anonymize data, please do not touch the amounts. Everything else should be fine to change.

**Comment by TeemuLattiLuja** [comment]
I took the SIE file to a closer look and talked with finance department. There was some vouchers that were not in balance according to SIE file. Basically if the type of VoucherRow was #RTRANS or #BTRANS it didn't balance. I then removed all the #RTRANS and #BTRANS rows and got it working by reading from file. 

I think I can work with this now.
Thanks for your time to help!

**Comment by idstam** [comment]
I don't know if you found them, but there are some options you can set on the SieDocument to ignore RTRANS and BTRANS while reading the file.

I'm glad you get some use out of this tool.

**Comment by TeemuLattiLuja** [comment]
Oh, I missed that.  That's actually really nice. 

Thanks for the tip!
